# CMakeLists.
# ===========

# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Laurent von Allmen

#------------------------------------------------------------------------
# Author:	Laurent von Allmen	The 2025-01-01
# Modifs:
#
# Project:	uKOS-X
# Goal:		CMake file to set up the building for uKOS-X system.
#
#   (c) 2025-2026, Laurent von Allmen
#   ---------------------------------
#                                              __ ______  _____
#   Edo. Franzi                         __  __/ //_/ __ \/ ___/
#   5-Route de Cheseaux                / / / / ,< / / / /\__ \
#   CH 1400 Cheseaux-Noréaz           / /_/ / /| / /_/ /___/ /
#                                     \__,_/_/ |_\____//____/
#   edo.franzi@ukos.ch
#
#   Description: Lightweight, real-time multitasking operating
#   system for embedded microcontroller and DSP-based systems.
#
#   Permission is hereby granted, free of charge, to any person
#   obtaining a copy of this software and associated documentation
#   files (the "Software"), to deal in the Software without restriction,
#   including without limitation the rights to use, copy, modify,
#   merge, publish, distribute, sublicense, and/or sell copies of the
#   Software, and to permit persons to whom the Software is furnished
#   to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be
#   included in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
#   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
#   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.
#
#------------------------------------------------------------------------

cmake_minimum_required(VERSION 3.26)

# uKOS-X CMake module setup
list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/../../../Mkfiles/cmake")

# Project path configuration
# - PATH_UKOS	--> Main uKOS-X folder
# - PATH_OSYS	--> Main OS folder
# - PATH_VARI	--> Projects Root Variant folder
# - PATH_BASE	--> Projects Root Base folder
# - PATH_PORT	--> PATH_UKOS/Ports
include(set-project-paths)

include(select-arm-toolchain)

project(
	Asmodee_H747_Variant_Test_CM7
	VERSION 1.0
	LANGUAGES C
)

# Microcontroller description (mandatory variables)
set(SOC STM32H747)
set(CORE CORTEX_M7)

# Apply project settings
include(proj_config)

# SOC has cache
add_compile_definitions(CACHE_D_S)
file(APPEND "${ARTEFACTS_DIR}/FLASH.cnf" "-DCACHE_D_S ")

# Customisation of firmware copyright text
add_compile_definitions(
	"uKOS_NAME="
	"uKOS_OWNER=(c) LvA"
)

# Flash programming script selection
set(BURN jlinkexe)

# Extra compilation options
add_compile_options(
	-g3 # include extra information for debugger
	-Os # optimisation
)

# TinyUSB integration (must be before library definitions)
add_TinyUSB(
	SPEED HS
	PROFILE cdc_video
)

# Sources
# -------

# First piece of code (privileged)
set(FIRST_P
	${PATH_PORT}/EquatesModels/SOCs/${SOC}/Runtime/first.c
)

# Runtime & common components (privileged) -> librtcb_p.a
add_library(rtcb_p ${RTCB_P})
target_sources(rtcb_p PRIVATE
	${PATH_OSYS}/Boots/boot/boot.c
	${PATH_PORT}/EquatesModels/Cores/${CORE}/Runtime/syscallDispatcher.c
	${PATH_PORT}/EquatesModels/Generic/Runtime/crt0.c
	${PATH_PORT}/EquatesModels/SOCs/${SOC}/Runtime/cache.c
	${PATH_BASE}/Runtime/cmns.c
	${PATH_BASE}/Runtime/exce.c
	${PATH_VARI}/Runtime/init.c
)
target_link_libraries(rtcb_p PUBLIC system_compiler_flags)

# uKernel components (privileged) -> libkern_p.a
add_library(kern_p)
target_sources(kern_p PRIVATE
	${PATH_OSYS}/Lib_kernels/kern/debug.c
	${PATH_OSYS}/Lib_kernels/kern/identifier.c
	${PATH_OSYS}/Lib_kernels/kern/kern.c
	${PATH_OSYS}/Lib_kernels/kern/lists.c
	${PATH_OSYS}/Lib_kernels/kern/mailboxes.c
	${PATH_OSYS}/Lib_kernels/kern/mutexes.c
	${PATH_OSYS}/Lib_kernels/kern/pools.c
	${PATH_OSYS}/Lib_kernels/kern/preciseSignals.c
	${PATH_OSYS}/Lib_kernels/kern/processes.c
	${PATH_OSYS}/Lib_kernels/kern/scheduler.c
	${PATH_OSYS}/Lib_kernels/kern/semaphores.c
	${PATH_OSYS}/Lib_kernels/kern/signals.c
	${PATH_OSYS}/Lib_kernels/kern/softwareTimers.c
	${PATH_OSYS}/Lib_kernels/kern/statistics.c
	${PATH_OSYS}/Lib_kernels/kern/temporal.c
	${PATH_BASE}/Lib_kernels/kern/stub_kern_kernel.c
)
target_link_libraries(kern_p PUBLIC system_compiler_flags)

# uKernel components (user) -> libkern_u.a
add_library(kern_u)
target_sources(kern_u PRIVATE
	${PATH_OSYS}/Lib_kernels/kern/privileges.c
	${PATH_OSYS}/Lib_kernels/kern/xLibrary.c
)
target_link_libraries(kern_u PUBLIC system_compiler_flags)

# Lib_xxxx components (privileged) -> liblibx_p.a
add_library(libx_p)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_cryptographics/random/random.c CONFIG_MAN_RANDOM_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_generics/asmp/asmp.c CONFIG_MAN_ASMP_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_generics/calendar/calendar.c CONFIG_MAN_CALENDAR_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_generics/machine/machine.c CONFIG_MAN_MACHINE_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_generics/memo/memo.c CONFIG_MAN_MEMO_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_generics/record/record.c CONFIG_MAN_RECORD_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_generics/system/system.c CONFIG_MAN_SYSTEM_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/i2c/i2c.c CONFIG_MAN_I2C_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/i2c0/i2c0.c CONFIG_MAN_I2C0_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/imager/imager.c CONFIG_MAN_IMAGER_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/imu/imu.c CONFIG_MAN_IMU_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/led/led.c CONFIG_MAN_LED_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/spi/spi.c CONFIG_MAN_SPI_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/spi0/spi0.c CONFIG_MAN_SPI0_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/switch/switch.c CONFIG_MAN_SWITCH_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/temperature/temperature.c CONFIG_MAN_TEMPERATURE_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_peripherals/watchdog/watchdog.c CONFIG_MAN_WATCHDOG_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_serials/cdc0/cdc0.c CONFIG_MAN_CDC0_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_serials/serial/serial.c CONFIG_MAN_SERIAL_S)
add_source_with_define(libx_p ${PATH_OSYS}/Lib_serials/urt0/urt0.c CONFIG_MAN_URT0_S)
target_sources(libx_p PRIVATE
	${PATH_BASE}/Lib_cryptographics/random/stub_random.c
	${PATH_BASE}/Lib_generics/machine/stub_machine.c
	${PATH_BASE}/Lib_peripherals/i2c0/stub_i2c0_si2c3.c
	${PATH_BASE}/Lib_peripherals/spi0/stub_spi0_sspi2.c
	${PATH_BASE}/Lib_peripherals/watchdog/stub_watchdog.c
	${PATH_COMX}/Lib_generics/asmp/stub_asmp_hsem.c
	${PATH_VARI}/Lib_peripherals/imager/stub_imager_mt9v03x.c
	${PATH_VARI}/Lib_peripherals/imu/stub_imu_lsm9ds1.c
	${PATH_VARI}/Lib_peripherals/led/stub_led.c
	${PATH_VARI}/Lib_peripherals/switch/stub_switch.c
	${PATH_VARI}/Lib_peripherals/temperature/stub_temperature_lsm9ds1.c
	${PATH_VARI}/Lib_serials/urt0/stub_urt0_usart6.c
)
target_link_libraries(libx_p PUBLIC system_compiler_flags ${TINYUSB})

# Lib_xxxx components (user) -> liblibx_u.a
add_library(libx_u)
add_source_with_define(libx_u ${PATH_OSYS}/Lib_generics/newlib/newlib.c CONFIG_MAN_NEWLIB_S)
add_source_with_define(libx_u ${PATH_OSYS}/Lib_generics/text/text.c CONFIG_MAN_TEXT_S)
add_source_with_define(libx_u ${PATH_OSYS}/Lib_neurals/mlpn/mlpn.c CONFIG_MAN_MLPN_S)
target_link_libraries(libx_u PUBLIC system_compiler_flags)

# Shared components (privileged) -> libshar_p.a
add_library(shar_p)
target_sources(shar_p PRIVATE
	${PATH_VARI}/Shared/shared_spi0/shared_spi0.c
)
target_link_libraries(shar_p PUBLIC system_compiler_flags)

# Process components (privileged) -> libproc_p.a
add_library(proc_p)
target_sources(proc_p PRIVATE
	${PATH_OSYS}/Daemons/idle/idle.c
	${PATH_OSYS}/Daemons/mcore/mcore.c
	${PATH_OSYS}/Daemons/rtc/rtc.c
	${PATH_OSYS}/Daemons/stack/stack.c
	${PATH_OSYS}/Daemons/stimer/stimer.c
)
target_link_libraries(proc_p PUBLIC system_compiler_flags)

# Process components (user) -> libproc_u.a
add_library(proc_u)
target_sources(proc_u PRIVATE
	${PATH_OSYS}/Processes/alive/alive.c
	${PATH_OSYS}/Processes/launcher/launcher.c
	${PATH_OSYS}/Processes/startUp/startUp.c
	${PATH_OSYS}/Processes/TinyUSB/TinyUSB.c
	${PATH_BASE}/Processes/alive/stub_alive.c
	${PATH_VARI}/Processes/startUp/stub_startUp.c
	${PATH_BASE}/Processes/TinyUSB/stub_TinyUSB.c
)
target_link_libraries(proc_u PUBLIC system_compiler_flags ${TINYUSB})

# CLI components (user) -> libtool_u.a
add_library(tool_u)
target_sources(tool_u PRIVATE
	${PATH_OSYS}/CLI/bangla/BaNgLa.c
	${PATH_OSYS}/CLI/bench/bench.c
	${PATH_OSYS}/CLI/bench/bench_00.c
	${PATH_OSYS}/CLI/bench/bench_01.c
	${PATH_OSYS}/CLI/bench/bench_02.c
	${PATH_OSYS}/CLI/bench/bench_03.c
	${PATH_OSYS}/CLI/bench/bench_04.c
	${PATH_OSYS}/CLI/bench/bench_05.c
	${PATH_OSYS}/CLI/console/console.c
	${PATH_OSYS}/CLI/cycle/cycle.c
	${PATH_OSYS}/CLI/date/date.c
	${PATH_OSYS}/CLI/dump/dump.c
	${PATH_OSYS}/CLI/dumplog/dumplog.c
	${PATH_OSYS}/CLI/dumptrace/dumptrace.c
	${PATH_OSYS}/CLI/echo/echo.c
	${PATH_OSYS}/CLI/fill/fill.c
	${PATH_OSYS}/CLI/hexloader/hexloader.c
	${PATH_OSYS}/CLI/kill/kill.c
	${PATH_OSYS}/CLI/list/list.c
	${PATH_OSYS}/CLI/man/man.c
	${PATH_OSYS}/CLI/memory/memory.c
	${PATH_OSYS}/CLI/microPython/microPython.c
	${PATH_OSYS}/CLI/mutex/mutex.c
	${PATH_OSYS}/CLI/object/object.c
	${PATH_OSYS}/CLI/process/process.c
	${PATH_OSYS}/CLI/restart/restart.c
	${PATH_OSYS}/CLI/rnd/rnd.c
	${PATH_OSYS}/CLI/run/run.c
	${PATH_OSYS}/CLI/semaphore/semaphore.c
	${PATH_OSYS}/CLI/sloader/sloader.c
	${PATH_OSYS}/CLI/szkern/szkern.c
	${PATH_OSYS}/CLI/test_malloc/test_malloc.c
	${PATH_OSYS}/CLI/test_mcore/test_mcore.c
	${PATH_OSYS}/CLI/test_ram/test_ram.c
	${PATH_OSYS}/CLI/uKOS/uKOS.c
	${PATH_OSYS}/CLI/viewer/viewer_uvc0_imager.c
	${PATH_OSYS}/CLI/viewer/viewer.c
	${PATH_OSYS}/CLI/wki2c/wki2c.c
	${PATH_OSYS}/CLI/wkserial/wkserial.c
	${PATH_OSYS}/CLI/wkspi/wkspi.c
)
target_link_libraries(tool_u PUBLIC system_compiler_flags ${TINYUSB})

# All library components
set(UKOS_COMPONENTS rtcb_p kern_p kern_u libx_p libx_u shar_p proc_p proc_u tool_u ${TINYUSB})

# Optional manager
add_MicroPython()

# System configuration flags

# Statistics support
add_compile_definitions(KKERN_WITH_STATISTICS_S=true)

# Stack integrity monitoring
add_compile_definitions(
	KDAEMONS_ALERT_STACK_INT_S=false
	KDAEMONS_TIME_STACK_INT=10000
	KDAEMONS_WITH_STACK_INT_S=true
)

# Hardware RTC support
add_compile_definitions(KCALENDAR_WITH_HW_RTC_S=true)

# Apply system configuration
include(system)
